### ISSUE TITLE
support 1.0 yaml syntax

### ISSUE THREAD

**Issue by bradrydzewski** [microadam/drone-config-changeset-conditional#1]
awesome work!  would this also support the 1.0 yaml syntax? I only ask because the example in the readme is using the 0.8 yaml syntax.

```
kind: pipeline
name: default

steps:
- name: frontend
   image: node
   commands:
     - cd app
     - npm run test
   when:
      changeset:
        includes: [ **/**.js, **/**.css, **/**.html ]

trigger:
  changeset:
    includes: [ **/**.go ]
```
