### ISSUE TITLE
Exception while using the plugin

### ISSUE THREAD

**Issue by rverma-nikiai** [microadam/drone-config-changeset-conditional#11]
drone.yml
```
kind: pipeline
name: default

clone:
  depth: 1
  
steps:
- name: test
  image: alpine
  commands:
   - echo hi
  when:
    changeset:
      includes: [ "OWNERS", "README.*" ]
        
- name: finisher
  image: alpine
  commands:
   - echo finished


trigger:
  branch:
    - master
```

```
Processing...
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at app.post (/app/plugin.js:37:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
