### ISSUE TITLE
include vs includes?

### ISSUE THREAD

**Issue by jimsheldon** [microadam/drone-config-changeset-conditional#18]
Hello!

We are very interested in using this plugin, but we are hoping to "future proof" it as much as possible.

Currently the required syntax is:
```yaml
   when:
      changeset:
        includes: [ **/**.js, **/**.css, **/**.html ]
```
and
```yaml
trigger:
  changeset:
    includes: [ **/**.go ]
```
All other drone syntax seems to use `include` rather than `includes`.  Would you consider a new version of this plugin with a breaking change that switches to `include` to match drone's official syntax?  Or maybe there is a way this plugin could support both `include` and `includes`?
