### ISSUE TITLE
Does it support drone 0.8 configuration?

### ISSUE THREAD

**Issue by sudip-moengage** [microadam/drone-config-changeset-conditional#20]
I am migrating from drone enterprise 1.0 to woodpecker (fork of drone 0.8).

My configuration which is written on 1.0 is working fine. But, when I downgrade to 0.8, drone enterprise and woodpecker both running pipeline even if files which required to be changed to trigger builds are not changed.

drone.yml:
```yaml
pipeline:
  build:
    image: plugins/ecr
    context: ./helm/
    dockerfile: ./helm/Dockerfile
    repo: account.dkr.ecr.us-east-1.amazonaws.com/sre/tiller-ca
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - ${DRONE_COMMIT_BRANCH}
      - latest
    when:
      changeset:
        includes: [ helm/** ]
```

But this 1.0 configuration works for enterprise:
```yaml
---
kind: pipeline
name: helm

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

steps:
- name: Helm Tiller CA build
  image: docker:dind
  commands:
    - sleep 10
    - docker build ./helm/
  volumes:
    - name: dockersock
      path: /var/run
  when:
    changeset:
      includes: [ helm/** ]
- name: Helm Tiller CA publish
  image: plugins/ecr
  settings:
    context: ./helm/
    dockerfile: ./helm/Dockerfile
    repo: account.dkr.ecr.us-east-1.amazonaws.com/sre/tiller-ca
    registry: account.dkr.ecr.us-east-1.amazonaws.com
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - ${DRONE_COMMIT_BRANCH}
      - latest
  when:
    changeset:
      includes: [ helm/** ]

trigger:
  branch: master
  event: [ push ]
```

Config-changeset-plugin logs:
```
Processing...
Files changed: [ '.drone.yml', 'README.md' ]
Processing...
Files changed: [ '.drone.yml', 'README.md' ]
```
