### ISSUE TITLE
undefined after retrieving config from a (private) repo

### ISSUE THREAD

**Issue by ferhatelmas** [microadam/drone-config-changeset-conditional#4]
```
drone-changeset_1  | Files changed: [ '.drone.yml' ]
drone-changeset_1  | (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'filter' of undefined
drone-changeset_1  |     at parsedYaml.map.py (/app/plugin.js:60:35)
drone-changeset_1  |     at Array.map (<anonymous>)
drone-changeset_1  |     at app.post (/app/plugin.js:48:36)
drone-changeset_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

drone 1.0.1 on docker-compose multi-machine setup.

**Comment by microadam** [comment]
Hello, could you post an example YAML please? Hard to tell what is going in without one :)

**Comment by ferhatelmas** [comment]
Thanks, sure, following should be the config at the time:

https://gist.github.com/ferhatelmas/b860f59f9b8d5f0a43f7160641ee3638

**Comment by microadam** [comment]
so your first pipeline doesn't have any `steps`

```
---
kind: pipeline
name: clone

platform:
  os: linux
  arch: amd64

clone:
  depth: 100

trigger:
  branch:
    exclude:
    - develop
  event:
  - push
  - pull_request
  - tag

---
```

Is this intentional? It seems like a fairly redundant pipeline?

 This plugin currently assumes that every pipeline has a `steps` block
